/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
	watch "k8s.io/client-go/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretsGetter has a method to return a SecretInterface.
// A group's client should implement this interface.
type SecretsGetter interface {
	Secrets(namespace string) SecretInterface
}

// SecretInterface has methods to work with Secret resources.
type SecretInterface interface {
	Create(ctx context.Context, secret *v1.Secret, options metav1.CreateOptions) (*v1.Secret, error)
	Update(ctx context.Context, secret *v1.Secret, options metav1.UpdateOptions) (*v1.Secret, error)
	Delete(ctx context.Context, name string, options metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, options metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(ctx context.Context, name string, options metav1.GetOptions) (*v1.Secret, error)
	List(ctx context.Context, options metav1.ListOptions) (*v1.SecretList, error)
	Watch(ctx context.Context, options metav1.ListOptions) (watch.Watcher, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, options metav1.PatchOptions, subresources ...string) (result *v1.Secret, err error)
	Apply(ctx context.Context, secret *corev1.SecretApplyConfiguration, options metav1.ApplyOptions) (result *v1.Secret, err error)
	SecretExpansion
}

// secrets implements SecretInterface
type secrets struct {
	client rest.Interface
	ns     string
}

// newSecrets returns a Secrets
func newSecrets(c *CoreV1Client, namespace string) *secrets {
	return &secrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secret, and returns the corresponding secret object, and an error if there is any.
func (c *secrets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Secret, err error) {
	result = &v1.Secret{}
	err = c.client.Get().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		Name(name).
		VersionedParams(&options).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Secrets that match those selectors.
func (c *secrets) List(ctx context.Context, options metav1.ListOptions) (result *v1.SecretList, err error) {
	var timeout time.Duration
	if options.TimeoutSeconds != nil {
		timeout = time.Duration(*options.TimeoutSeconds) * time.Second
	}
	result = &v1.SecretList{}
	err = c.client.Get().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		VersionedParams(&options).
		Timeout(timeout).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Watcher that watches the requested secrets.
func (c *secrets) Watch(ctx context.Context, options metav1.ListOptions) (watch.Watcher, error) {
	var timeout time.Duration
	if options.TimeoutSeconds != nil {
		timeout = time.Duration(*options.TimeoutSeconds) * time.Second
	}
	options.Watch = true
	return c.client.Get().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		VersionedParams(&options).
		Timeout(timeout).
		ExpectKind("Secret").
		Watch(ctx)
}

// Create takes the representation of a secret and creates it.  Returns the server's representation of the secret, and an error, if there is any.
func (c *secrets) Create(ctx context.Context, secret *v1.Secret, options metav1.CreateOptions) (result *v1.Secret, err error) {
	result = &v1.Secret{}
	err = c.client.Post().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		VersionedParams(&options).
		Body(secret).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secret and updates it. Returns the server's representation of the secret, and an error, if there is any.
func (c *secrets) Update(ctx context.Context, secret *v1.Secret, options metav1.UpdateOptions) (result *v1.Secret, err error) {
	result = &v1.Secret{}
	err = c.client.Put().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		Name(secret.Name).
		VersionedParams(&options).
		Body(secret).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secret and deletes it. Returns an error if one occurs.
func (c *secrets) Delete(ctx context.Context, name string, options metav1.DeleteOptions) error {
	return c.client.Delete().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		Name(name).
		Body(&options).
		ExpectKind("Secret").
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secrets) DeleteCollection(ctx context.Context, options metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		VersionedParams(&listOptions).
		Timeout(timeout).
		Body(&options).
		ExpectKind("Secret").
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secret.
func (c *secrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, options metav1.PatchOptions, subresources ...string) (result *v1.Secret, err error) {
	result = &v1.Secret{}
	err = c.client.Patch(pt).
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&options).
		Body(data).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied secret.
func (c *secrets) Apply(ctx context.Context, secret *corev1.SecretApplyConfiguration, options metav1.ApplyOptions) (result *v1.Secret, err error) {
	if secret == nil {
		return nil, fmt.Errorf("secret provided to Apply must not be nil")
	}
	patchOpts := options.ToPatchOptions()
	data, err := json.Marshal(secret)
	if err != nil {
		return nil, err
	}
	name := secret.Name
	if name == nil {
		return nil, fmt.Errorf("secret.Name must be provided to Apply")
	}
	result = &v1.Secret{}
	err = c.client.Patch(types.ApplyPatchType).
		ApiPath("/api").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("secrets").
		Name(*name).
		VersionedParams(&patchOpts).
		Body(data).
		ExpectKind("Secret").
		Do(ctx).
		Into(result)
	return
}
