/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "k8s.io/api/batch/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	batchv1 "k8s.io/client-go/applyconfigurations/batch/v1"
	watch "k8s.io/client-go/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JobsGetter has a method to return a JobInterface.
// A group's client should implement this interface.
type JobsGetter interface {
	Jobs(namespace string) JobInterface
}

// JobInterface has methods to work with Job resources.
type JobInterface interface {
	Create(ctx context.Context, job *v1.Job, options metav1.CreateOptions) (*v1.Job, error)
	Update(ctx context.Context, job *v1.Job, options metav1.UpdateOptions) (*v1.Job, error)
	UpdateStatus(ctx context.Context, job *v1.Job, options metav1.UpdateOptions) (*v1.Job, error)
	Delete(ctx context.Context, name string, options metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, options metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(ctx context.Context, name string, options metav1.GetOptions) (*v1.Job, error)
	List(ctx context.Context, options metav1.ListOptions) (*v1.JobList, error)
	Watch(ctx context.Context, options metav1.ListOptions) (watch.Watcher, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, options metav1.PatchOptions, subresources ...string) (result *v1.Job, err error)
	Apply(ctx context.Context, job *batchv1.JobApplyConfiguration, options metav1.ApplyOptions) (result *v1.Job, err error)
	ApplyStatus(ctx context.Context, job *batchv1.JobApplyConfiguration, options metav1.ApplyOptions) (result *v1.Job, err error)
	JobExpansion
}

// jobs implements JobInterface
type jobs struct {
	client rest.Interface
	ns     string
}

// newJobs returns a Jobs
func newJobs(c *BatchV1Client, namespace string) *jobs {
	return &jobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the job, and returns the corresponding job object, and an error if there is any.
func (c *jobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Job, err error) {
	result = &v1.Job{}
	err = c.client.Get().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(name).
		VersionedParams(&options).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Jobs that match those selectors.
func (c *jobs) List(ctx context.Context, options metav1.ListOptions) (result *v1.JobList, err error) {
	var timeout time.Duration
	if options.TimeoutSeconds != nil {
		timeout = time.Duration(*options.TimeoutSeconds) * time.Second
	}
	result = &v1.JobList{}
	err = c.client.Get().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		VersionedParams(&options).
		Timeout(timeout).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Watcher that watches the requested jobs.
func (c *jobs) Watch(ctx context.Context, options metav1.ListOptions) (watch.Watcher, error) {
	var timeout time.Duration
	if options.TimeoutSeconds != nil {
		timeout = time.Duration(*options.TimeoutSeconds) * time.Second
	}
	options.Watch = true
	return c.client.Get().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		VersionedParams(&options).
		Timeout(timeout).
		ExpectKind("Job").
		Watch(ctx)
}

// Create takes the representation of a job and creates it.  Returns the server's representation of the job, and an error, if there is any.
func (c *jobs) Create(ctx context.Context, job *v1.Job, options metav1.CreateOptions) (result *v1.Job, err error) {
	result = &v1.Job{}
	err = c.client.Post().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		VersionedParams(&options).
		Body(job).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a job and updates it. Returns the server's representation of the job, and an error, if there is any.
func (c *jobs) Update(ctx context.Context, job *v1.Job, options metav1.UpdateOptions) (result *v1.Job, err error) {
	result = &v1.Job{}
	err = c.client.Put().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(job.Name).
		VersionedParams(&options).
		Body(job).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *jobs) UpdateStatus(ctx context.Context, job *v1.Job, options metav1.UpdateOptions) (result *v1.Job, err error) {
	result = &v1.Job{}
	err = c.client.Put().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(job.Name).
		SubResource("status").
		VersionedParams(&options).
		Body(job).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the job and deletes it. Returns an error if one occurs.
func (c *jobs) Delete(ctx context.Context, name string, options metav1.DeleteOptions) error {
	return c.client.Delete().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(name).
		Body(&options).
		ExpectKind("Job").
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jobs) DeleteCollection(ctx context.Context, options metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		VersionedParams(&listOptions).
		Timeout(timeout).
		Body(&options).
		ExpectKind("Job").
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched job.
func (c *jobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, options metav1.PatchOptions, subresources ...string) (result *v1.Job, err error) {
	result = &v1.Job{}
	err = c.client.Patch(pt).
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&options).
		Body(data).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied job.
func (c *jobs) Apply(ctx context.Context, job *batchv1.JobApplyConfiguration, options metav1.ApplyOptions) (result *v1.Job, err error) {
	if job == nil {
		return nil, fmt.Errorf("job provided to Apply must not be nil")
	}
	patchOpts := options.ToPatchOptions()
	data, err := json.Marshal(job)
	if err != nil {
		return nil, err
	}
	name := job.Name
	if name == nil {
		return nil, fmt.Errorf("job.Name must be provided to Apply")
	}
	result = &v1.Job{}
	err = c.client.Patch(types.ApplyPatchType).
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(*name).
		VersionedParams(&patchOpts).
		Body(data).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *jobs) ApplyStatus(ctx context.Context, job *batchv1.JobApplyConfiguration, options metav1.ApplyOptions) (result *v1.Job, err error) {
	if job == nil {
		return nil, fmt.Errorf("job provided to Apply must not be nil")
	}
	patchOpts := options.ToPatchOptions()
	data, err := json.Marshal(job)
	if err != nil {
		return nil, err
	}

	name := job.Name
	if name == nil {
		return nil, fmt.Errorf("job.Name must be provided to Apply")
	}

	result = &v1.Job{}
	err = c.client.Patch(types.ApplyPatchType).
		ApiPath("/apis").
		GroupVersion(v1.SchemeGroupVersion).
		Namespace(c.ns).
		Resource("jobs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts).
		Body(data).
		ExpectKind("Job").
		Do(ctx).
		Into(result)
	return
}
